#!/usr/bin/env python3
"""Rebuild data/pulls.js from data/possible-pulls.csv.

Run after editing the CSV:  python3 tools/build-data.py
The output is a plain JS file (not JSON) so the site works when opened
straight from disk as well as when hosted.
"""
import csv
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "possible-pulls.csv"
OUT = ROOT / "data" / "pulls.js"

CATS = {"main": "m", "alt_art_SIR": "a", "promo": "p"}

sets, set_idx = [], {}
editions = {}

with SRC.open(newline="", encoding="utf-8") as f:
    for r in csv.DictReader(f):
        ed = r["edition"].strip().lower()
        spot = int(r["spot"])
        s = r["set"].strip()
        if s not in set_idx:
            set_idx[s] = len(sets)
            sets.append(s)
        spots = editions.setdefault(ed, {})
        groups = spots.setdefault(spot, {})
        groups.setdefault(r["pokemon"].strip(), []).append([
            r["card_name"].strip(),
            r["card_number"].strip(),
            set_idx[s],
            CATS.get(r["category"].strip(), "m"),
            r["rarity"].strip(),
        ])

data = {
    "sets": sets,
    "editions": {
        ed: [
            {"spot": n, "groups": [{"pokemon": p, "cards": c} for p, c in groups.items()]}
            for n, groups in sorted(spots.items())
        ]
        for ed, spots in editions.items()
    },
}

OUT.write_text(
    "/* Generated by tools/build-data.py from data/possible-pulls.csv — do not edit by hand. */\n"
    "window.VAULT_PULLS = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n",
    encoding="utf-8",
)
print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")
